import categorical_semantics_formal_languages_foundation_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace categorical_semantics_formal_languages_foundation_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end categorical_semantics_formal_languages_foundation_canonical_lane_mathlib
end HautevilleHouse
